/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as OrgRouteImport } from './routes/org'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesNamespaceRouteImport } from './routes/sources.$namespace'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as BillingPlansRouteImport } from './routes/billing_.plans'
import { Route as SourcesAddPluginKeyRouteImport } from './routes/sources.add.$pluginKey'
import { Route as SettingsBillingPlansRouteImport } from './routes/settings.billing_.plans'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNamespaceRoute = SourcesNamespaceRouteImport.update({
  id: '/sources/$namespace',
  path: '/sources/$namespace',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const BillingPlansRoute = BillingPlansRouteImport.update({
  id: '/billing_/plans',
  path: '/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesAddPluginKeyRoute = SourcesAddPluginKeyRouteImport.update({
  id: '/sources/add/$pluginKey',
  path: '/sources/add/$pluginKey',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingPlansRoute = SettingsBillingPlansRouteImport.update({
  id: '/billing_/plans',
  path: '/billing/plans',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/connections': typeof ConnectionsRoute
  '/org': typeof OrgRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tools': typeof ToolsRoute
  '/billing/plans': typeof BillingPlansRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/settings/billing/plans': typeof SettingsBillingPlansRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/connections': typeof ConnectionsRoute
  '/org': typeof OrgRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tools': typeof ToolsRoute
  '/billing/plans': typeof BillingPlansRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/settings/billing/plans': typeof SettingsBillingPlansRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/connections': typeof ConnectionsRoute
  '/org': typeof OrgRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tools': typeof ToolsRoute
  '/billing_/plans': typeof BillingPlansRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/settings/billing_/plans': typeof SettingsBillingPlansRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/connections'
    | '/org'
    | '/secrets'
    | '/settings'
    | '/tools'
    | '/billing/plans'
    | '/settings/billing'
    | '/sources/$namespace'
    | '/settings/billing/plans'
    | '/sources/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/connections'
    | '/org'
    | '/secrets'
    | '/settings'
    | '/tools'
    | '/billing/plans'
    | '/settings/billing'
    | '/sources/$namespace'
    | '/settings/billing/plans'
    | '/sources/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/connections'
    | '/org'
    | '/secrets'
    | '/settings'
    | '/tools'
    | '/billing_/plans'
    | '/settings/billing'
    | '/sources/$namespace'
    | '/settings/billing_/plans'
    | '/sources/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  ConnectionsRoute: typeof ConnectionsRoute
  OrgRoute: typeof OrgRoute
  SecretsRoute: typeof SecretsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  BillingPlansRoute: typeof BillingPlansRoute
  SourcesNamespaceRoute: typeof SourcesNamespaceRoute
  SourcesAddPluginKeyRoute: typeof SourcesAddPluginKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$namespace': {
      id: '/sources/$namespace'
      path: '/sources/$namespace'
      fullPath: '/sources/$namespace'
      preLoaderRoute: typeof SourcesNamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/billing_/plans': {
      id: '/billing_/plans'
      path: '/billing/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof BillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/add/$pluginKey': {
      id: '/sources/add/$pluginKey'
      path: '/sources/add/$pluginKey'
      fullPath: '/sources/add/$pluginKey'
      preLoaderRoute: typeof SourcesAddPluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing_/plans': {
      id: '/settings/billing_/plans'
      path: '/billing/plans'
      fullPath: '/settings/billing/plans'
      preLoaderRoute: typeof SettingsBillingPlansRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsBillingPlansRoute: typeof SettingsBillingPlansRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsBillingPlansRoute: SettingsBillingPlansRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  ConnectionsRoute: ConnectionsRoute,
  OrgRoute: OrgRoute,
  SecretsRoute: SecretsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ToolsRoute: ToolsRoute,
  BillingPlansRoute: BillingPlansRoute,
  SourcesNamespaceRoute: SourcesNamespaceRoute,
  SourcesAddPluginKeyRoute: SourcesAddPluginKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
