// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

import type {} from "@useautumn/sdk";

declare module "@useautumn/sdk" {
  // Features
  export const domainVerification: Feature;
  export const executions: Feature;
  export const persistentSandbox: Feature;

  // Plans
  export const free: Plan;
  export const pro: Plan;

  // Base types
  export type Feature = import("./autumn.config").Feature;
  export type Plan = import("./autumn.config").Plan;
}
