// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

import type {} from "@useautumn/sdk";

declare module "@useautumn/sdk" {
  // Features
  export const seats: Feature;
  export const managedAuth: Feature;
  export const remoteMcp: Feature;
  export const hostedWorkerFallback: Feature;

  // Plans
  export const pro: Plan;

  // Base types
  export type Feature = import("./autumn.config").Feature;
  export type Plan = import("./autumn.config").Plan;
}
